// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.stephen.learning.grpc.service;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QueryUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stephen.learning.grpc.service.QueryUserRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code com.stephen.learning.grpc.service.QueryUserRequest}
   */
  public  static final class QueryUserRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stephen.learning.grpc.service.QueryUserRequest)
      QueryUserRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryUserRequest.newBuilder() to construct.
    private QueryUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryUserRequest() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryUserRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stephen.learning.grpc.service.User.QueryUserRequest.class, com.stephen.learning.grpc.service.User.QueryUserRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stephen.learning.grpc.service.User.QueryUserRequest)) {
        return super.equals(obj);
      }
      com.stephen.learning.grpc.service.User.QueryUserRequest other = (com.stephen.learning.grpc.service.User.QueryUserRequest) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stephen.learning.grpc.service.User.QueryUserRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stephen.learning.grpc.service.QueryUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stephen.learning.grpc.service.QueryUserRequest)
        com.stephen.learning.grpc.service.User.QueryUserRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stephen.learning.grpc.service.User.QueryUserRequest.class, com.stephen.learning.grpc.service.User.QueryUserRequest.Builder.class);
      }

      // Construct using com.stephen.learning.grpc.service.User.QueryUserRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserRequest_descriptor;
      }

      public com.stephen.learning.grpc.service.User.QueryUserRequest getDefaultInstanceForType() {
        return com.stephen.learning.grpc.service.User.QueryUserRequest.getDefaultInstance();
      }

      public com.stephen.learning.grpc.service.User.QueryUserRequest build() {
        com.stephen.learning.grpc.service.User.QueryUserRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stephen.learning.grpc.service.User.QueryUserRequest buildPartial() {
        com.stephen.learning.grpc.service.User.QueryUserRequest result = new com.stephen.learning.grpc.service.User.QueryUserRequest(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stephen.learning.grpc.service.User.QueryUserRequest) {
          return mergeFrom((com.stephen.learning.grpc.service.User.QueryUserRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stephen.learning.grpc.service.User.QueryUserRequest other) {
        if (other == com.stephen.learning.grpc.service.User.QueryUserRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stephen.learning.grpc.service.User.QueryUserRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stephen.learning.grpc.service.User.QueryUserRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stephen.learning.grpc.service.QueryUserRequest)
    }

    // @@protoc_insertion_point(class_scope:com.stephen.learning.grpc.service.QueryUserRequest)
    private static final com.stephen.learning.grpc.service.User.QueryUserRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stephen.learning.grpc.service.User.QueryUserRequest();
    }

    public static com.stephen.learning.grpc.service.User.QueryUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryUserRequest>
        PARSER = new com.google.protobuf.AbstractParser<QueryUserRequest>() {
      public QueryUserRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryUserRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryUserRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryUserRequest> getParserForType() {
      return PARSER;
    }

    public com.stephen.learning.grpc.service.User.QueryUserRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryUserResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stephen.learning.grpc.service.QueryUserResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
     */
    int getGenderValue();
    /**
     * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
     */
    com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType getGender();

    /**
     * <code>.google.protobuf.Timestamp birthDate = 3;</code>
     */
    boolean hasBirthDate();
    /**
     * <code>.google.protobuf.Timestamp birthDate = 3;</code>
     */
    com.google.protobuf.Timestamp getBirthDate();
    /**
     * <code>.google.protobuf.Timestamp birthDate = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getBirthDateOrBuilder();

    /**
     * <code>string email = 4;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 4;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string address = 5;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 5;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();
  }
  /**
   * Protobuf type {@code com.stephen.learning.grpc.service.QueryUserResponse}
   */
  public  static final class QueryUserResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stephen.learning.grpc.service.QueryUserResponse)
      QueryUserResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QueryUserResponse.newBuilder() to construct.
    private QueryUserResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QueryUserResponse() {
      name_ = "";
      gender_ = 0;
      email_ = "";
      address_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QueryUserResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (birthDate_ != null) {
                subBuilder = birthDate_.toBuilder();
              }
              birthDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(birthDate_);
                birthDate_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stephen.learning.grpc.service.User.QueryUserResponse.class, com.stephen.learning.grpc.service.User.QueryUserResponse.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 2;
    private int gender_;
    /**
     * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
     */
    public com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType getGender() {
      com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType result = com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType.valueOf(gender_);
      return result == null ? com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType.UNRECOGNIZED : result;
    }

    public static final int BIRTHDATE_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp birthDate_;
    /**
     * <code>.google.protobuf.Timestamp birthDate = 3;</code>
     */
    public boolean hasBirthDate() {
      return birthDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp birthDate = 3;</code>
     */
    public com.google.protobuf.Timestamp getBirthDate() {
      return birthDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp birthDate = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getBirthDateOrBuilder() {
      return getBirthDate();
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 5;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (gender_ != com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType.MALE.getNumber()) {
        output.writeEnum(2, gender_);
      }
      if (birthDate_ != null) {
        output.writeMessage(3, getBirthDate());
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, address_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (gender_ != com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType.MALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, gender_);
      }
      if (birthDate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getBirthDate());
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, address_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stephen.learning.grpc.service.User.QueryUserResponse)) {
        return super.equals(obj);
      }
      com.stephen.learning.grpc.service.User.QueryUserResponse other = (com.stephen.learning.grpc.service.User.QueryUserResponse) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && gender_ == other.gender_;
      result = result && (hasBirthDate() == other.hasBirthDate());
      if (hasBirthDate()) {
        result = result && getBirthDate()
            .equals(other.getBirthDate());
      }
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getAddress()
          .equals(other.getAddress());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      if (hasBirthDate()) {
        hash = (37 * hash) + BIRTHDATE_FIELD_NUMBER;
        hash = (53 * hash) + getBirthDate().hashCode();
      }
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stephen.learning.grpc.service.User.QueryUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stephen.learning.grpc.service.User.QueryUserResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stephen.learning.grpc.service.QueryUserResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stephen.learning.grpc.service.QueryUserResponse)
        com.stephen.learning.grpc.service.User.QueryUserResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stephen.learning.grpc.service.User.QueryUserResponse.class, com.stephen.learning.grpc.service.User.QueryUserResponse.Builder.class);
      }

      // Construct using com.stephen.learning.grpc.service.User.QueryUserResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        gender_ = 0;

        if (birthDateBuilder_ == null) {
          birthDate_ = null;
        } else {
          birthDate_ = null;
          birthDateBuilder_ = null;
        }
        email_ = "";

        address_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stephen.learning.grpc.service.User.internal_static_com_stephen_learning_grpc_service_QueryUserResponse_descriptor;
      }

      public com.stephen.learning.grpc.service.User.QueryUserResponse getDefaultInstanceForType() {
        return com.stephen.learning.grpc.service.User.QueryUserResponse.getDefaultInstance();
      }

      public com.stephen.learning.grpc.service.User.QueryUserResponse build() {
        com.stephen.learning.grpc.service.User.QueryUserResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stephen.learning.grpc.service.User.QueryUserResponse buildPartial() {
        com.stephen.learning.grpc.service.User.QueryUserResponse result = new com.stephen.learning.grpc.service.User.QueryUserResponse(this);
        result.name_ = name_;
        result.gender_ = gender_;
        if (birthDateBuilder_ == null) {
          result.birthDate_ = birthDate_;
        } else {
          result.birthDate_ = birthDateBuilder_.build();
        }
        result.email_ = email_;
        result.address_ = address_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stephen.learning.grpc.service.User.QueryUserResponse) {
          return mergeFrom((com.stephen.learning.grpc.service.User.QueryUserResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stephen.learning.grpc.service.User.QueryUserResponse other) {
        if (other == com.stephen.learning.grpc.service.User.QueryUserResponse.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (other.hasBirthDate()) {
          mergeBirthDate(other.getBirthDate());
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stephen.learning.grpc.service.User.QueryUserResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stephen.learning.grpc.service.User.QueryUserResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
       */
      public int getGenderValue() {
        return gender_;
      }
      /**
       * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
       */
      public com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType getGender() {
        com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType result = com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType.valueOf(gender_);
        return result == null ? com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
       */
      public Builder setGender(com.stephen.learning.grpc.service.GenderTypeOuterClass.GenderType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.stephen.learning.grpc.service.GenderType gender = 2;</code>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp birthDate_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> birthDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      public boolean hasBirthDate() {
        return birthDateBuilder_ != null || birthDate_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      public com.google.protobuf.Timestamp getBirthDate() {
        if (birthDateBuilder_ == null) {
          return birthDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : birthDate_;
        } else {
          return birthDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      public Builder setBirthDate(com.google.protobuf.Timestamp value) {
        if (birthDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          birthDate_ = value;
          onChanged();
        } else {
          birthDateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      public Builder setBirthDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (birthDateBuilder_ == null) {
          birthDate_ = builderForValue.build();
          onChanged();
        } else {
          birthDateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      public Builder mergeBirthDate(com.google.protobuf.Timestamp value) {
        if (birthDateBuilder_ == null) {
          if (birthDate_ != null) {
            birthDate_ =
              com.google.protobuf.Timestamp.newBuilder(birthDate_).mergeFrom(value).buildPartial();
          } else {
            birthDate_ = value;
          }
          onChanged();
        } else {
          birthDateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      public Builder clearBirthDate() {
        if (birthDateBuilder_ == null) {
          birthDate_ = null;
          onChanged();
        } else {
          birthDate_ = null;
          birthDateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getBirthDateBuilder() {
        
        onChanged();
        return getBirthDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getBirthDateOrBuilder() {
        if (birthDateBuilder_ != null) {
          return birthDateBuilder_.getMessageOrBuilder();
        } else {
          return birthDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : birthDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp birthDate = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getBirthDateFieldBuilder() {
        if (birthDateBuilder_ == null) {
          birthDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getBirthDate(),
                  getParentForChildren(),
                  isClean());
          birthDate_ = null;
        }
        return birthDateBuilder_;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 4;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 5;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 5;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 5;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stephen.learning.grpc.service.QueryUserResponse)
    }

    // @@protoc_insertion_point(class_scope:com.stephen.learning.grpc.service.QueryUserResponse)
    private static final com.stephen.learning.grpc.service.User.QueryUserResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stephen.learning.grpc.service.User.QueryUserResponse();
    }

    public static com.stephen.learning.grpc.service.User.QueryUserResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryUserResponse>
        PARSER = new com.google.protobuf.AbstractParser<QueryUserResponse>() {
      public QueryUserResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new QueryUserResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QueryUserResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryUserResponse> getParserForType() {
      return PARSER;
    }

    public com.stephen.learning.grpc.service.User.QueryUserResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stephen_learning_grpc_service_QueryUserRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stephen_learning_grpc_service_QueryUserRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stephen_learning_grpc_service_QueryUserResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stephen_learning_grpc_service_QueryUserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022!com.stephen.learning.grpc." +
      "service\032\037google/protobuf/timestamp.proto" +
      "\032\020GenderType.proto\" \n\020QueryUserRequest\022\014" +
      "\n\004name\030\001 \001(\t\"\257\001\n\021QueryUserResponse\022\014\n\004na" +
      "me\030\001 \001(\t\022=\n\006gender\030\002 \001(\0162-.com.stephen.l" +
      "earning.grpc.service.GenderType\022-\n\tbirth" +
      "Date\030\003 \001(\0132\032.google.protobuf.Timestamp\022\r" +
      "\n\005email\030\004 \001(\t\022\017\n\007address\030\005 \001(\t2\211\001\n\013UserS" +
      "ervice\022z\n\rqueryUserInfo\0223.com.stephen.le" +
      "arning.grpc.service.QueryUserRequest\0324.c" +
      "om.stephen.learning.grpc.service.QueryUs" +
      "erResponseb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.stephen.learning.grpc.service.GenderTypeOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_stephen_learning_grpc_service_QueryUserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stephen_learning_grpc_service_QueryUserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stephen_learning_grpc_service_QueryUserRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_stephen_learning_grpc_service_QueryUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_stephen_learning_grpc_service_QueryUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stephen_learning_grpc_service_QueryUserResponse_descriptor,
        new java.lang.String[] { "Name", "Gender", "BirthDate", "Email", "Address", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.stephen.learning.grpc.service.GenderTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
